### PR TITLE
Revert "Add linter config"

### PR DESCRIPTION
**Pull request by abulte**
Reverts ecolabdata/ecospheres-front#54

Can we please revert that and then do it again when #53 and #56 are merged? I don't really want to handle some awful conflicts :-/

Since it's automated it shouldn't be a problem to do it again later.

### CODE REVIEW

**Comment by maukoquiroga** [comment]
Ops, sure.

**Comment by abulte** [comment]
NB: @streino it might be cleaner to rewrite history by force pushing HEAD~1, up to you

**Comment by streino** [comment]
Oops, sorry I thought @abulte you sent the original linter PR -- didn't realize @maukoquiroga had already jumped in 😅 
If you want me to force push I can but hold on your merges until then 🙏

**Comment by maukoquiroga** [comment]
Double oops, we've had 1m of distance in our messages. Up to you folks 🙏

**Pull request merged**
